version: '3'

services:
  php:
    container_name: "bookme-php"
    build:
      context: .
      args:
        - USER_ID=1000
        - USER=bookme
      dockerfile: Dockerfile  
    volumes:
      - ./:/var/www/bookme
    restart: always
    networks:
      - bookme

  web:
    container_name: "bookme-web"
    image: nginx:1.24
    working_dir: /var/www/bookme
    volumes:
      - ./:/var/www/bookme:delegated
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    restart: always
    ports:
      - "${WEB_DOCKER_PORT}:80"
    networks:
      - bookme

  db:
    container_name: "bookme-db"
    platform: linux/x86-64
    image: postgres:15.4-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_USERNAME}
    restart: always
    volumes:
      - ~/data/db/postgres/bookme:/var/lib/postgresql/data
    ports:
      - "${DB_DOCKER_PORT}:5432"
    networks:
      - bookme

networks:
  bookme:
    name: bookme
    driver: bridge